/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '활용 가이드',
      items: [
        'guides/component-basic',
        'guides/lifecycle',
        'guides/map-support',
        {
          type: 'category',
          label: '지도',
          items: [
            'guides/map-basic',
            'guides/map-initialize',
            'guides/map-event',
            'guides/map-cache',
            'guides/map-throttling',
            'guides/map-loading-component',
            'guides/map-debug',
          ]
        },
        {
          type: 'category',
          label: '오버레이 - 마커',
          items: [
            'guides/marker-basic',
            'guides/marker-polygon',
            'guides/marker-circle',
          ]
        },
        'guides/overlay-control',
        'guides/overlay-polyline',
        'guides/overlay-polygon',
      ],
    },
    {
      type: 'category',
      label: '고급 가이드',
      items: [
        'advanced-guides/performance',
        'advanced-guides/util',
      ]
    }
  ],

};

module.exports = sidebars;
